# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"

# Enable mouse support
set -g mouse on

# Start window indexing at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift-alt-(H|L) to move windows
bind -n M-H previous-window
bind -n M-L next-window

# Set prefix to <C-Space>
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Make yank keys vim-like
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Disable confirm
bind-key x kill-pane
bind-key & kill-window

# Open new panes in current directory
bind '-' split-window -v -c "#{pane_current_path}"
bind '[' split-window -h -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'alexwforsythe/tmux-which-key'

run '~/.tmux/plugins/tpm/tpm'
