# Meant to be sourced by hyprland.conf
# This file is meant to be modified by scripts like ./scripts/float-rule.sh


windowrule = float on, match:class zen, match:title Library, min_size 1000 600, xray off
