[mgr]
prepend_keymap = [
  { on = "y", run = [
    'shell -- echo %s | xclip -i -selection clipboard -t text/uri-list',
    "yank",
  ], desc = "Yank selected files to system clipboard" },
  { on = "M", run = "plugin mount", desc = "Mount selected files" },
]
append_keymap = [
  { on = "R", run = "rename --force --cursor=before_ext", desc = "Force rename" },
  { on = [
    "g",
    "t",
  ], run = "cd ~/.local/share/Trash/files", desc = "Go to trash" },
  { on = [
    "g",
    "D",
  ], run = "cd ~/Documents", desc = "Go to Documents" },
  { on = [
    "g",
    "p",
  ], run = "cd ~/projects/", desc = "Go to Projects" },
  { on = [
    "g",
    "P",
  ], run = "cd ~/Pictures", desc = "Go to Pictures" },
  { on = [
    "g",
    "C",
  ], run = "cd ~/obsidian/the-vault/Areas/College", desc = "Go to College" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/obsidian/the-vault", desc = "Go to Vault" },
  { on = [
    "g",
    "V",
  ], run = "cd ~/Videos/", desc = "Go to Videos" },
  { on = [
    "g",
    ";",
  ], run = "shell --orphan kitty", desc = "Open Kitty Here" },
]
