[opener]
edit = [{ run = 'nvim "$@"', block = true }]

satty = [{ run = 'satty --filename %s', orphan = true, desc = "satty" }]

mpv = [{ run = 'mpv %s', orphan = true, desc = "mpv" }]

picker = [
  { run = '~/scripts/open-with.sh "$@"', block = true, desc = "App Picker" },
]

zathura = [{ run = 'zathura %s', orphan = true, desc = "zathura" }]
okular = [{ run = 'okular %s', orphan = true, desc = "okular" }]

[open]
prepend_rules = [
  { mime = "image/*", use = [
    "open",
    "satty",
    "picker",
  ] },
  { mime = "video/*", use = [
    "open",
    "mpv",
    "picker",
  ] },
  { mime = "application/pdf", use = [
    "open",
    "okular",
    "picker",
  ] },
  { mime = "application/epub+zip", use = [
    "open",
    "zathura",
    "picker",
  ] },
]

append_rules = [{ mime = "*", use = ["picker"] }]

[mgr]
sort_by = "natural"
