[opener]
edit = [{ run = 'nvim "$@"', block = true }]

satty = [{ run = 'satty --filename %s', orphan = true, desc = "satty" }]

[open]
prepend_rules = [{ mime = "image/*", use = ["open", "satty"] }]

[mgr]
sort_by = "natural"
